version: '3.8'

services:
  ocr-bot:
    build: .
    image: lowara1243/ocr-bot:1.0
    container_name: telegram_ocr_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./src/ocr_bot/database:/app/src/ocr_bot/database
      - ./src/ocr_bot/logs:/app/src/ocr_bot/logs
      - ./src/ocr_bot/temp_images:/app/src/ocr_bot/temp_images
    tty: true